#!/bin/bash

# Clean up unused Docker images
docker image prune -f

# Clean up unused Docker volumes (optional, uncomment to enable)
docker volume prune -f

# Show running Docker containers
docker ps

# Build and run Docker containers in detached mode
docker compose up --build -d

# Clean up unused Docker images again after the containers are built
docker image prune -f

# Clean up unused Docker volumes (optional, uncomment to enable)
# docker volume prune -f

# Show running Docker containers again
docker ps

# Run Django migrations inside the Django container
docker exec -it fin_flow_container python manage.py migrate



# Follow the logs of the Django app container (or replace 'fin_flow_container' with your container name)
docker logs -f fin_flow_container
