# Generated by Django 5.1.7 on 2025-04-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone_num",
            new_name="phone_number",
        ),
    ]
