# Generated by Django 5.1.7 on 2025-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication", "0002_rename_phone_num_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
