# Generated by Django 5.1.7 on 2025-04-03 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication", "0003_user_is_verified_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="bvn",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="nin",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="transaction_pin",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
    ]
