# Generated by Django 5.1.7 on 2025-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_authentication",
            "0004_alter_useraccount_bvn_alter_useraccount_nin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
