# Generated by Django 5.1.7 on 2025-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication", "0006_onetimepassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
